repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["sshse", "--explicit-package-bases"]
        pass_filenames: false
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", "sshse", "-q"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python
        language: system
        args: ["-m", "pytest"]
        pass_filenames: false
        always_run: true
